Factory/Models/DesignTimeDBContextFactory.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace Factory.Models
{
  public class FactoryContextFactory : IDesignTimeDbContextFactory<FactoryContext>
  {

    FactoryContext IDesignTimeDbContextFactory<FactoryContext>.CreateDbContext(string[] args)
    {
      IConfigurationRoot configuration = new ConfigurationBuilder()
          .SetBasePath(Directory.GetCurrentDirectory())
          .AddJsonFile("appsettings.json")
          .Build();

      var builder = new DbContextOptionsBuilder<FactoryContext>();

      builder.UseMySql(configuration["ConnectionStrings:DefaultConnection"], ServerVersion.AutoDetect(configuration["ConnectionStrings:DefaultConnection"]));

      return new FactoryContext(builder.Options);
    }
  }
}

Factory/Models/Engineer.cs
using System.Collections.Generic;
using System;

namespace Factory.Models
{
  public class Engineer
  {
    public Engineer()
    {
      this.JoinEntities = new HashSet<EngineerMachine>();
    }

    public int EngineerId { get; set; }
    public string Name { get; set; }
    public DateTime LicenseDate { get; set; }
    public virtual ICollection<EngineerMachine> JoinEntities { get; set; }
  }
}

Factory/Models/EngineerMachine.cs
namespace Factory.Models
{
  public class EngineerMachine
  {
    public int EngineerMachineId { get; set; }
    public int MachineId { get; set; }
    public int EngineerId { get; set; }
    public virtual Machine Machine { get; set; }
    public virtual Engineer Engineer { get; set; }
  }
}

Factory/Models/FactoryContext.cs
using Microsoft.EntityFrameworkCore;

namespace Factory.Models
{
  public class FactoryContext : DbContext
  {
    public virtual DbSet<Engineer> Engineers { get; set; }
    public DbSet<Machine> Machines { get; set; }
    public DbSet<EngineerMachine> EngineerMachine { get; set; }

    public FactoryContext(DbContextOptions options) : base(options) { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

Factory/Models/Machine.cs
using System.Collections.Generic;

namespace Factory.Models
{
  public class Machine
  {
    public Machine()
    {
      this.JoinEntities = new HashSet<EngineerMachine>();
    }

    public int MachineId { get; set; }
    public string Name { get; set; }
    public bool Operational { get; set; }

    public virtual ICollection<EngineerMachine> JoinEntities { get; }
  }
}

Factory/Controllers/EngineersController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;
using System;

namespace Factory.Controllers
{
  public class EngineersController : Controller
  {
    private readonly FactoryContext _db;

    public EngineersController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Engineer> model = _db.Engineers.ToList();
      return View(model);
    }
    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Engineer engineer)
    {
      _db.Engineers.Add(engineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Details(int id)
    {
      var thisEngineer = _db.Engineers
          .Include(engineer => engineer.JoinEntities)
          .ThenInclude(join => join.Machine)
          .FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }
    public ActionResult Edit(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult Edit(Engineer engineer)
    {
      _db.Entry(engineer).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Delete(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      _db.Engineers.Remove(thisEngineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Factory.Controllers
{
  public class HomeController : Controller
  {

    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }
  }
}

Factory/Controllers/MachinesController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers
{
  public class MachinesController : Controller
  {
    private readonly FactoryContext _db;

    public MachinesController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Machines.ToList());
    }
    public ActionResult Create()
    {
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Machine machine, int EngineerId)
    {
      _db.Machines.Add(machine);
      _db.SaveChanges();
      if (EngineerId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { EngineerId = EngineerId, MachineId = machine.MachineId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Details(int id)
    {
      var thisMachine = _db.Machines
          .Include(machine => machine.JoinEntities)
          .ThenInclude(join => join.Engineer)
          .FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }
    public ActionResult Edit(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult Edit(Machine machine, int EngineerId)
    {
      if (EngineerId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { EngineerId = EngineerId, MachineId = machine.MachineId });
      }
      _db.Entry(machine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult AddEngineer(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult AddEngineer(Machine machine, int EngineerId)
    {
      if (EngineerId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { EngineerId = EngineerId, MachineId = machine.MachineId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Delete(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    [HttpPost]
    public ActionResult DeleteEngineer(int joinId)
    {
      var joinEntry = _db.EngineerMachine.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachine.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Views/Engineers/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h4><span class="underLine">Add A New Engineer</span></h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name, new { required = "required" })
  @Html.Label("License Renewal Date")
  @Html.TextBoxFor(model => model.LicenseDate, "{0:MM/dd/yyyy}", new { @class = "form-control datepicker", @alt = "date",
@minlength = "10", @placeholder = DateTime.Now.Date.ToString("MM/dd/yyyy"), @maxlength = "10", @data_val="true"})

  <input type="submit" value="Add New Engineer" class="btn btn-outline-success" />
}
<div class="flex">
  @Html.ActionLink("Show All Engineers", "Index", "Engineers", null, new { @class = "btn btn-outline-dark"})
  @Html.ActionLink("Home", "Index", "Home", null, new {@class = "btn btn-outline-dark"})
</div>

Factory/Views/Engineers/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Are you sure you want to delete @Html.DisplayFor(model => model.Name)?</h2>

@using (Html.BeginForm())
{
  <input type="submit" value="Delete" class="btn btn-outline-danger" class="delete" />
}
<div class="flex">
  @Html.ActionLink("Back to Engineers", "Index", "Engineers", null, new { @class = "btn btn-outline-dark" })
</div>

Factory/Views/Engineers/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer;

<h2><span class="underLine">Details for @Html.DisplayFor(model => model.Name)</span></h2>


@if (@Model.JoinEntities.Count == 0)
{
  <p>This engineer is not licensed to repair any machines</p>
}
else
{
  <h5 class="yesGood">License Renewed: @Model.LicenseDate.ToString("MMM dd, yyyy") </h5>
  <h4>Machines this engineer is licensed to repair:</h4>
  <ul>
  @foreach (var join in Model.JoinEntities)
    {
      <h5>@Html.ActionLink($"{join.Machine.Name}", "Details","Machines", new { id = join.Machine.MachineId })</h5>
    }
  </ul>
}

<div class="flex">
  @Html.ActionLink("Edit Engineer", "Edit", "Engineers", new { id =Model.EngineerId }, new { @class = "btn btn-outline-dark"})
  @Html.ActionLink("Delete Engineer", "Delete", "Engineers", new { id =Model.EngineerId }, new { @class = "btn btn-outline-dark"})
  @Html.ActionLink("View all Engineers", "Index", "Engineers", null, new { @class = "btn btn-outline-dark"})
  @Html.ActionLink("Home", "Index", "Home", null, new { @class = "btn btn-outline-dark"})
</div>

Factory/Views/Engineers/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Edit @Html.DisplayFor(model => model.Name)</h2>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.EngineerId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)
  @Html.Label("License Renewal Date")
  @Html.TextBoxFor(model => model.LicenseDate, "{0:MM/dd/yyyy}", new { @class = "form-control datepicker", @alt = "date",
@minlength = "10", @placeholder = DateTime.Now.Date.ToString("MM/dd/yyyy"), @maxlength = "10", @data_val="false"})

  <input type="submit" value="Save" class="btn btn-outline-primary" />
}
@Html.ActionLink("View all Engineers", "Index", "Engineers", null, new { @class = "btn btn-outline-dark" })

Factory/Views/Engineers/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;

<h1>Engineers</h1>

@if (@Model.Count == 0)
{
  <h3>No Engineers have been added yet!</h3>
}

<ul>
  @foreach (Engineer engineer in Model)
  {
    <li>@Html.ActionLink($"{engineer.Name}", "Details", new { id = engineer.EngineerId })</li>
  }
</ul>

<div class="flex">
  @Html.ActionLink("Add New Engineer", "Create", "Engineers", null, new {@class = "btn btn-outline-dark"})
  @Html.ActionLink("Home", "Index", "Home", null, new {@class = "btn btn-outline-dark"})
</div>

Factory/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Welcome, Dr. Sillystringz!</h1>
<h3>What would you like to do?</h3>
<div class="flex">
  @Html.ActionLink("See All Engineers", "Index", "Engineers", null, new { @class = "btn btn-outline-dark"})
  @Html.ActionLink("See All Machines", "Index", "Machines", null, new { @class = "btn btn-outline-dark"})
</div>

Factory/Views/Machines/AddEngineer.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Add a licensed engineer able to repair @Html.DisplayFor(model => model.Name)</h2>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)

  @Html.Label("Select Engineer")
  @Html.DropDownList("EngineerId", "-select-")

  <input type="submit" value="Save" class="btn btn-outline-primary" />
}

@Html.ActionLink("Back to Machines", "Index", "Machines", null, new { @class = "btn btn-outline-dark"})

Factory/Views/Machines/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h4><span class="underLine">Add A New Machine</span></h4>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name, new {required = "required"})
  @Html.Label("This Machine Operational When Checked")
  @Html.CheckBoxFor(model => model.Operational)

  @Html.Label("Select Engineer")
  @Html.DropDownList("EngineerId", "-select-")

  <input type="submit" value="Add New Machine" class="btn btn-outline-success" />
}
<div class="flex">
  @Html.ActionLink("Show All Machines", "Index", "Machines", null, new {@class = "btn btn-outline-dark"})
  @Html.ActionLink("Home", "Index", "Home", null, new {@class = "btn btn-outline-dark"})
</div>

Factory/Views/Machines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Are you sure you want to delete @Html.DisplayFor(model => model.Name)?</h2>

@using (Html.BeginForm())
{
  <input type="submit" value="Delete" class="btn btn-outline-danger" />
}
<div class="flex">
  @Html.ActionLink("Back to Machines", "Index", "Machines", null, new { @class = "btn btn-outline-dark"})
</div>

Factory/Views/Machines/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2><span class="underLine">Details for @Html.DisplayFor(model => model.Name)</span></h2>

@if (@Model.Operational == true)
{
  <h5 class="yesGood">This Machine is currently operational</h5>
}
else
{
  <h5 class="noGood">This Machine is not currently operational</h5>
}
@if (@Model.JoinEntities.Count == 0)
{
  <p>There are no engineers licensed to repair this machine</p>
}
else
{
  <h4>Engineers licensed to repair this machine:</h4>
  <ul>
  @foreach(var join in Model.JoinEntities)
  {
    <h5>@Html.ActionLink($"{join.Engineer.Name}", "Details","Engineers", new { id = join.Engineer.EngineerId })</h5>
    @using (Html.BeginForm("DeleteEngineer", "Machines"))
    {
      @Html.Hidden("joinId", @join.EngineerMachineId)
      <input type="submit" value="Delete" class="btn btn-outline-danger" />
      <hr style="width: 75%;"/>
    }
  }
  </ul>
}

<div class="flex">
@Html.ActionLink("Edit Machine", "Edit", "Machines", new {id = Model.MachineId}, new { @class = "btn btn-outline-dark" })
@Html.ActionLink("Delete Machine", "Delete", "Machines", new {id = Model.MachineId}, new { @class = "btn btn-outline-dark"})
@Html.ActionLink("Add an Engineer", "AddEngineer", new { id = Model.MachineId }, new { @class = "btn btn-outline-dark" })
@Html.ActionLink("View all Machines", "Index", "Machines", null, new { @class = "btn btn-outline-dark" })
</div>

Factory/Views/Machines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Edit @Html.DisplayFor(model => model.Name)</h2>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)
  @Html.Label("This Machine Operational When Checked")
  @Html.CheckBoxFor(model => model.Operational)

  @Html.Label("Select Engineer")
  @Html.DropDownList("EngineerId", "-select-")

  <input type="submit" value="Save" class="btn btn-outline-primary" />
}

<div class="flex">
  @Html.ActionLink("Back to Machines", "Index", "Machines", null, new { @class = "btn btn-outline-dark"})
  @Html.ActionLink("Home", "Index", "Home", null, new { @class = "btn btn-outline-dark"})
</div>

Factory/Views/Machines/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;
@model List<Factory.Models.Machine>;

<h1>Machines</h1>

@if (@Model.Count == 0)
{
  <h3>No Machines have been added yet!</h3>
}

<ul>
  @foreach (Machine machine in Model)
  {
    <li>@Html.ActionLink($"{machine.Name}", "Details", new { id = machine.MachineId })</li>
  }
</ul>

<div class="flex">
  @Html.ActionLink("Home", "Index", "Home", null, new { @class = "btn btn-outline-dark"})
  @Html.ActionLink("Add New Machine", "Create", "Machines", null, new {@class = "btn btn-outline-dark"})
</div>

Factory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Dr. Sillystringz Factory</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" href="~/css/styles.css">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Fugaz+One&display=swap" rel="stylesheet">

</head>

<body>
  <div class="container">
    <div class="card">
      @RenderBody()
    </div>
  </div>
</body>


</html>